### ISSUE TITLE
Error during migration from Ruby 3.0.x to 3.1.x

### ISSUE THREAD

**Issue by guillaumebriday-pa** [kreeti/kt-paperclip#102]
Hi 👋 

First thanks for this fork and the work you're doing!

Everything was running smoothly until I tried to upgrade my app from Ruby 3.0.x to Ruby 3.1.x. I changed nothing else than the ruby version and the method `validates_attachment_content_type` starts to fail with this error:

<img width="914" alt="Screenshot 2022-12-06 at 09 33 12" src="https://user-images.githubusercontent.com/89008587/205940433-19135601-0447-4db7-be4a-dacaf80ba151.png">

I have no idea why, the data look correct but the record cannot be save 

Any idea why?

Thanks in advance

**Comment by josh-m-sharpe** [comment]
Getting the same thing.  Came here to find this bug report.

```
class PushNotificationMemberList < ApplicationRecord
  belongs_to :push_notification

  has_attached_file :csv, s3_permissions: :private

  validates_attachment :csv,
    content_type: { content_type: ["text/csv", "text/plain"] }
```

```
FactoryBot.define do
  factory :push_notification_member_list do
    push_notification

    after(:build) do |pnml|
      pnml.csv = Rack::Test::UploadedFile.new("test/fixtures/test_member_list.csv")
      pnml.csv_content_type = 'text/csv'
    end
  end
end
```

```
* push_notification_member_list - Validation failed: Csv has contents that are not what they are reported to be (ActiveRecord::RecordInvalid)
    test/models/factory_lint_test.rb:5:in `block in <class:FactoryLintTest>'
```

**Comment by josh-m-sharpe** [comment]
I've made this change to how I attach files in my test suite and this issue seems to be resolved:

```
-      object.csv = Rack::Test::UploadedFile.new("test/fixtures/test_member_list.csv")
-      object.csv_content_type = 'text/csv'
+      object.csv = Rack::Test::UploadedFile.new("test/fixtures/test_member_list.csv", 'text/csv', 'test_member_list.csv')
```

It's not quite clear to me why that is -- or why, for example, it only breaks for me in CircleCI-land (I think Ubuntu) but my tests worked fine in OSX-land.

**Comment by matthewford** [comment]
Yup seeing this too. trying to patch this with validate_media_type: false

**Comment by josh-m-sharpe** [comment]
> Yup seeing this too. trying to patch this with validate_media_type: false

This seems like a bit of a sledgehammer.

----

In my case, I am using CircleCI's docker image https://hub.docker.com/r/cimg/rubyfrom 
Turns out the 3.1.3 version of this image doesn't have `file` installed.  So I fixed with a simple `apt-get install file`

I think, but am not 100% positive, this would've helped:
https://github.com/kreeti/kt-paperclip/pull/103

**Comment by masterkain** [comment]
I'm not 100% positive this is related but I'm getting this:

```
2023-02-27T16:02:43.935Z pid=1 tid=6lf9 WARN: NoMethodError: undefined method `_read_attribute' for :read_attribute_for_validation:Symbol
2023-02-27T16:02:43.935Z pid=1 tid=6lf9 WARN: /bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4.2/lib/active_model/attribute_methods.rb:277:in `artwork_content_type'
/bundle/vendor/ruby/3.2.0/bundler/gems/kt-paperclip-11abf222dc31/lib/paperclip/validators/attachment_content_type_validator.rb:19:in `validate_each'
/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4.2/lib/active_model/validator.rb:153:in `block in validate'
/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4.2/lib/active_model/validator.rb:149:in `each'
/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4.2/lib/active_model/validator.rb:149:in `validate'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:423:in `block in make_lambda'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:686:in `catch'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:686:in `block in default_terminator'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:200:in `block in halting'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:595:in `block in invoke_before'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:595:in `each'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:595:in `invoke_before'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:106:in `run_callbacks'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:929:in `_run_validate_callbacks'
/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4.2/lib/active_model/validations.rb:406:in `run_validations!'
/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4.2/lib/active_model/validations/callbacks.rb:117:in `block in run_validations!'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:107:in `run_callbacks'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/callbacks.rb:929:in `_run_validation_callbacks'
/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4.2/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4.2/lib/active_model/validations.rb:337:in `valid?'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/validations.rb:68:in `valid?'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/validations.rb:84:in `perform_validations'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/validations.rb:47:in `save'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/transactions.rb:298:in `block in save'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/transactions.rb:298:in `save'
/bundle/vendor/ruby/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/suppressor.rb:50:in `save'
/usr/src/app/app/workers/media_artwork.rb:29:in `perform'
```

**Comment by ssinghi** [comment]
@josh-m-sharpe I have merged your PR, can this issue be closed now? Thanks!
