### ISSUE TITLE
undefined method `_read_attribute' for :read_attribute_for_validation:Symbol with Rails 7.0.4.1 

### ISSUE THREAD

**Issue by geoffharcourt** [kreeti/kt-paperclip#107]
**Describe the bug**
After upgrading to Rails 7.0.4.1 we're seeing frequent but not consistent failures across many branches related to a `NoMethodError` called in Paperclip.

**To Reproduce**
1. an example failing model has a content type validation:

```
class MultimediaAsset < ApplicationRecord
  has_attached_file :upload
  validates_attachment_content_type :upload, content_type: /\Aimage\/.*\Z/
end
```

2. We attempt to create one with a FactoryBot invocation:

```ruby
multimedia_asset = create(:multimedia_asset, :as_image)
```

**Expected behavior**
It looks like some of the security fixes between Rails 7.0.4 and 7.0.4.1 might have changed some private APIs that Paperclip was using.

**Screenshots**
Here's an example spec error:

```


Failure/Error: multimedia_asset = create(:multimedia_asset, :as_image)
--
  |  
  | NoMethodError:
  | undefined method `_read_attribute' for :read_attribute_for_validation:Symbol
  | # /bundle/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/validators/attachment_content_type_validator.rb:19:in `validate_each'
  | # /bundle/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/validators.rb:68:in `block in create_validating_before_filter'
  | # /bundle/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/callbacks.rb:28:in `block in hasta_la_vista_baby'
  | # /bundle/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/callbacks.rb:38:in `run_paperclip_callbacks'
  | # /bundle/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/attachment.rb:504:in `check_validity?'
  | # /bundle/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/attachment.rb:494:in `post_process'
  | # /bundle/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/attachment.rb:454:in `post_process_file'
  | # /bundle/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/attachment.rb:112:in `assign'
  | # /bundle/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:16:in `public_send'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:16:in `block (2 levels) in object'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:15:in `each'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:15:in `block in object'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/attribute_assigner.rb:14:in `object'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/evaluation.rb:13:in `object'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/strategy/create.rb:9:in `result'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/factory.rb:43:in `run'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:29:in `block in run'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:28:in `run'
  | # /bundle/ruby/3.2.0/gems/factory_bot-6.2.1/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
  | # ./spec/models/permission_asset_spec.rb:423:in `block (4 levels) in <main>'
```

**Additional context**

**Comment by geoffharcourt** [comment]
We think this is related to something else that happened at the same time as our Rails upgrade.

**Comment by geoffharcourt** [comment]
Notes for the future: this issue went away when we disabled YJIT in our CI environment, but we can't reproduce it in development environments with YJIT.

**Comment by slimdave** [comment]
We're getting this error on production, Ruby 3.2.0, Rails 7.1.4.2, kt-paperclip 7.2.2, only with RUBYOPT --enable-yjit

Without yjit we seem to be fine, though that's not very desirable.



Typical stacktrace

```
vendor/bundle/ruby/3.2.0/gems/activemodel-7.1.4.2/lib/active_model/attribute_methods.rb:284:in `file_content_type': undefined method `_read_attribute' for :read_attribute_for_validation:Symbol (NoMethodError)
    from vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.2/lib/paperclip/validators/attachment_content_type_validator.rb:19:in `validate_each'
    from vendor/bundle/ruby/3.2.0/gems/activemodel-7.1.4.2/lib/active_model/validator.rb:155:in `block in validate'
    from vendor/bundle/ruby/3.2.0/gems/activemodel-7.1.4.2/lib/active_model/validator.rb:151:in `each'
    from vendor/bundle/ruby/3.2.0/gems/activemodel-7.1.4.2/lib/active_model/validator.rb:151:in `validate'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:706:in `catch'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:706:in `block in default_terminator'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:203:in `block in halting'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:598:in `block in invoke_before'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:598:in `each'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:598:in `invoke_before'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:109:in `run_callbacks'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:952:in `_run_validate_callbacks'
    from vendor/bundle/ruby/3.2.0/gems/activemodel-7.1.4.2/lib/active_model/validations.rb:441:in `run_validations!'
    from vendor/bundle/ruby/3.2.0/gems/activemodel-7.1.4.2/lib/active_model/validations/callbacks.rb:115:in `block in run_validations!'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:110:in `run_callbacks'
    from vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:952:in `_run_validation_callbacks'
    from vendor/bundle/ruby/3.2.0/gems/activemodel-7.1.4.2/lib/active_model/validations/callbacks.rb:115:in `run_validations!'
    from vendor/bundle/ruby/3.2.0/gems/activemodel-7.1.4.2/lib/active_model/validations.rb:366:in `valid?'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/validations.rb:72:in `valid?'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/validations.rb:88:in `perform_validations'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/validations.rb:49:in `save'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/transactions.rb:309:in `block in save'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/transactions.rb:309:in `save'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/suppressor.rb:52:in `save'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/persistence.rb:895:in `block in update'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
    from vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.2/lib/active_record/persistence.rb:893:in `update'
```
